# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSAlbumList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSAlbumList
    pod 'Alamofire', '4.8.0'
    pod 'RxSwift', '4.4.2'

end
